name: Build and create zip skin file

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './src/package-lock.json'
    - name: Build
      run: |
        npm install
        npm run build
      working-directory: src
    - name: Archive builded skin as zip file
      uses: actions/upload-artifact@v3
      with:
        name: neowx-material-skin
        path: dist/
